name: custom-torizon-image
on:
  push:
    tags:
      - 'v*'
env:
  API_SECRET: ${{ secrets.TPS_V2_SECRET }}
  API_KEY: ${{ secrets.TPS_V2_API }}

jobs:
  make-release:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch source
        uses: actions/checkout@v3
      - name: Fetch TPS OAuth Token
        run:  |
              echo "$API_SECRET"
              echo "$API_KEY"
