name: custom-torizon-image
on:
  push:
    branches:

env:
  API_KEY: ${{ secrets.TPS_V2_API }}
  API_SECRET: ${{ secrets.TPS_V2_SECRET }}

jobs:
  make-release:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch source
        uses: actions/checkout@v3
      - name: Fetch API key
      - name: Fetch TPS OAuth Token
        run:  |
              ls
              python3 ./.github/workflows/push-to-tps.py
