name: custom-torizon-image
on:
  push:
    tags:
      - 'v*'
jobs:
  make-release:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch source
        uses: actions/checkout@v3
      - name: Fetch API key
        uses: mobiledevops/secret-to-file-action@v1
        with:
          base64-encoded-secret: ${{ secrets.TPS_V2_API }}
          filename: "api_key.txt"
          is-executable: false
          working-directory: "./"
      - name: Fetch API secret
        uses: mobiledevops/secret-to-file-action@v1
        with:
          base64-encoded-secret: ${{ secrets.TPS_V2_SECRET }}
          filename: "api_secret.txt"
          is-executable: false
          working-directory: "./"
      - name: Fetch TPS OAuth Token
        run:  |
              API_KEY=$(cat api_key.txt)
              API_SECRET=$(cat api_secret.txt)
              curl -s -X POST https://kc.torizon.io/auth/realms/ota-users/protocol/openid-connect/token -H 'Content-Type: application/x-www-form-urlencoded' -d "grant_type=client_credentials&client_id=${API_KEY}&client_secret=${API_SECRET}"
